version: '3'

services:
  server:
    container_name: executor-component
    image: executor-component:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8081}:${PORT:-8081}
    env_file:
      - .env
    networks:
      - executor-component-network
  gemma-2b:
    container_name: gemma-2b
    image: gemma-2b:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "gemma-2b"
        MODELFILE_PATH: "modelfiles/Modelfile-gemma-2b"
    ports:
      - "11434:11434"
    volumes:
      - gemma-2b_data:/root/.ollama
    networks:
      - executor-component-network
  gemma-7b:
    container_name: gemma-7b
    image: gemma-7b:latest
    build:
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "gemma-7b"
        MODELFILE_PATH: "modelfiles/Modelfile-gemma-7b"
    ports:
      - "11435:11434"
    volumes:
      - gemma-7b_data:/root/.ollama
    networks:
      - executor-component-network
  llama2-7b:
    container_name: llama2-7b
    image: llama2-7b:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "llama2-7b"
        MODELFILE_PATH: "modelfiles/Modelfile-llama2-7b"
    ports:
      - "11436:11434"
    volumes:
      - llama2-7b_data:/root/.ollama
    networks:
      - executor-component-network
  llama2-13b:
    container_name: llama2-13b
    image: llama2-13b:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "llama2-13b"
        MODELFILE_PATH: "modelfiles/Modelfile-llama2-13b"
    ports:
      - "11437:11434"
    volumes:
      - llama2-13b_data:/root/.ollama
    networks:
      - executor-component-network
  mistral-7b:
    container_name: mistral-7b
    image: mistral-7b:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile.predefined-model-modelfile
      args:
        MODEL_NAME: "mistral-7b"
        MODELFILE_PATH: "modelfiles/Modelfile-mistral-7b"
    ports:
      - "11438:11434"
    volumes:
      - mistral-7b_data:/root/.ollama
    networks:
      - executor-component-network
  

volumes:
  gemma-2b_data:
  gemma-7b_data:
  llama2-7b_data:
  llama2-13b_data:
  mistral-7b_data:

networks:
  executor-component-network:
    driver: bridge